#Docker commends
#docker build -t apigateway-layered -f Dockerfile.layered
#docker buikd -t apigateway -f Dockerfile | docker buikd -t apigateway .
version: '3'
services:


  db-products:
    image: mysql
    container_name: db-products
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eMedia_products_db
      MYSQL_USER: samim
      MYSQL_PASSWORD: db@password
    volumes:
      - ./db-products/data:/var/lib/mysql
#      - ./db-products/conf.d:/etc/mysql/conf.d
    ports:
      - '3307:3307'
#    expose:
#      - '3307'

  db-users:
    image: mysql
    container_name: db-users
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eMedia_db
      MYSQL_USER: samim
      MYSQL_PASSWORD: db@password
    volumes:
      - ./db-users/data:/var/lib/mysql
    ports:
      - '3306:3306'
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - '9411:9411'
  discovery-service:
    image: hafizullasamim/em-discovery-service
    container_name: discovery-service
    pull_policy: always
    ports:
      - '8761:8761'
#    entrypoint:
#      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - zipkin

  gateway-service:
    image: hafizullasamim/em-gateway-service
    container_name: gateway-service
    pull_policy: always
    ports:
      - '7070:7070'
    expose:
      - '7070'
#    entrypoint:
#      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - zipkin
      - discovery-service
  user-service:
    image: hafizullasamim/em-user-service
    container_name: user-service
    pull_policy: always
    ports:
      - '7074:7070'
    expose:
      - '7074'
#    entrypoint:
#      SPRING_DATASOURCE_URL=jdbc:mysql://db-users:3306/eMedia_db
#      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - zipkin
      - discovery-service
      - gateway-service
      - db-users

  products-service:
    image: hafizullasamim/em-products-service
    container_name: products-service
    pull_policy: always
    ports:
      - '7072:7070'
    expose:
      - '7072'
#    entrypoint:
#      SPRING_DATASOURCE_URL='jdbc:mysql://db-users:3306/eMedia_products_db'
#      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - zipkin
      - discovery-service
      - gateway-service
#      - db-users
      - db-products





