---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  ports:
    - name: http
      port: 7074
      targetPort: 7074
  selector:
    app: user-service

---
apiVersion: v1
kind: Service
metadata:
  name: products-service
  labels:
    app: products-service
spec:
  ports:
    - name: http
      port: 7072
      targetPort: 7072
  selector:
    app: products-service

---

apiVersion: v1
kind: Service
metadata:
  name: discovery-service
  labels:
    app: discovery-service
spec:
  ports:
    - name: http
      port: 8761
      targetPort: 8761
  selector:
    app: discovery-service

---

#apiVersion: v1
#kind: Pod
#metadata:
#  name: api-gateway-pod
#  labels:
#    app: api-gateway
#spec:
#  containers:
#    - name: api-gateway-container
#      image: your-dockerhub-username/api-gateway-image:tag
#      ports:
#        - containerPort: 8080
#      env:
#        - name: USER_SERVICE_URL
#          value: "http://user-service:8080"

---

apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  type: LoadBalancer
  ports:
    - port: 7070
      targetPort: 7070
  selector:
    app: gateway-service



#---

#apiVersion: v1
#kind: Service
#metadata:
#  name: db-users
#  labels:
#    app: user-service
#spec:
#  selector:
#    app: user-service
#  ports:
#    - name: mysql
#      port: 3306
#      targetPort: 3306
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: db-products
#  labels:
#    app: products-service
#spec:
#  selector:
#    app: products-service
#  ports:
#    - name: mysql
#      port: 3307
#      targetPort: 3307
#

---
apiVersion: v1
kind: Service
metadata:
  name: user-db-service
  labels:
    app: db-users
spec:
  selector:
    app: db-users
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306