apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
        - name: gateway-service
          image: hafizullasamim/em-gateway-service
          ports:
            - containerPort: 7070
          env:
            - name: USER_SERVICE_URL
              value: http://user-service:7074
#            - name: PRODUCT_SERVICE_URL
#              value: http://products-service:7072
            - name: DISCOVERY_SERVICE_URL
              value: http://discovery-service:8761


---

apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 7070
      targetPort: 7070
  selector:
    app: gateway-service